export { BiEdit } from "react-icons/bi";
export { MdOutlineRemoveRedEye } from "react-icons/md";
export { RiDeleteBinLine } from "react-icons/ri";
export { FaPlus } from "react-icons/fa6";
export { MdOutlineMail } from "react-icons/md";
export { LuPhoneCall } from "react-icons/lu";
export { GrLocation } from "react-icons/gr";
export { PiClockUser } from "react-icons/pi";
export { RiGraduationCapLine } from "react-icons/ri";
export { LiaUserClockSolid } from "react-icons/lia";
export { MdCalendarMonth } from "react-icons/md";
export { FaRegUserCircle } from "react-icons/fa";
export { RiUserFollowLine } from "react-icons/ri";
export { PiUserList } from "react-icons/pi";
export { TbAward } from "react-icons/tb";
export { PiCertificate } from "react-icons/pi";
export { FaGraduationCap } from "react-icons/fa6";
export { RiCustomerService2Fill } from "react-icons/ri";
export  { IoNotificationsOutline, IoReorderThreeOutline } from "react-icons/io5";
export { FaCog, FaSignOutAlt } from "react-icons/fa";
export { FaRegUser } from "react-icons/fa";