name: Build & Deploy

on:
  push:
    branches:
      - deploy

env:
  CI: false

  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Generate package-lock.json if missing
        run: |
          if [ ! -f package-lock.json ]; then
            echo "package-lock.json not found, generating..."
            npm install --package-lock-only
          else
            echo "package-lock.json found, skipping generation."
          fi

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript and Vite
        run: npm run build

      - name: Check if build directory exists
        run: |
          if [ -d "./dist" ]; then
            echo "Build directory 'dist' exists."
          else
            echo "Build directory 'dist' does not exist."
            ls -al  # List current directory contents for further investigation
            exit 1
          fi

      - name: List build directory contents
        run: ls -al ./dist

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/deploy'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ftp.opportunitiessharing.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}


