name: Build & Deploy

on:
  push:
    branches:
      - deploy

env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Generate package-lock.json if missing
        run: |
          if [ ! -f package-lock.json ]; then
            echo "package-lock.json not found, generating..."
            npm install --package-lock-only
          else
            echo "package-lock.json found, skipping generation."
          fi

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: |
          echo "Starting build..."
          npm run build
          echo "Build finished."

      - name: List root directory contents
        run: ls -al

      - name: List build directory contents
        run: ls -al ./build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/deploy'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build
